# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - release/*
    - refs/tags/*
  paths:
    include:
    - arm-helper/*
    - core/*
    - ingredient/*
    - system/*    
    - lerna.json
    - package.json

pr:
  branches:
    include:
    - master
    - release/*
    - refs/tags/*
  paths:
    include:
    - arm-helper/*
    - core/*
    - ingredient/*
    - system/*    
    - lerna.json
    - package.json

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: sudo npm install lerna@3.13.0 typescript@3.3.3 --global
  workingDirectory: ./
  displayName: NPM Install of Lerna & TypeScript

- bash: sudo lerna run clean:build
  workingDirectory: ./
  displayName: Lerna Run Clean Build

- bash: echo "Input Lerna Publish Script Here...."
  workingDirectory: ./
  displayName: Lerna Publish of all updated packages to NPM


